[package]
name = "meshbool-cpp"
version.workspace = true
edition.workspace = true

[lib]
name = "meshbool_unsafe"
crate-type = ["staticlib", "cdylib"]

[dependencies]
meshbool = { path = "../meshbool" }
nalgebra = { version = "0.34", default-features = false, features = ["std"] }
